---
# tasks file for build
- name: Install packages for build app
  apt: name={{ item }} state=present
  with_items:
    - docker.io

- name: Log into DockerHub
  docker_login:
    username: $DOCKER_USER
    password: $DOCKER_PASS

- name: build and push docker image
      docker_image:
        source: build
        build:
          path: /usr/src/app/Dockerfile
        name: anakin174/boxfuse-exam
        tag: latest
        target: prod
        push: yes
