---
# tasks file for build
- name: Install packages for build app
  apt: name={{ item }} state=present
  with_items:
    - git
    - maven

- name: Clone git repo
  git:
    repo: "https://github.com/boxfuse/boxfuse-sample-java-war-hello.git"
    dest: "/work"
    version: master

- name: Build java app
  command: mvn -f /work/pom.xml clean package
