---
- name: Build stage
  hosts: build
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Ensure packages is presented
      apt:
        pkg:
          - default-jdk
          - maven
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Ensure docker is presented
      pip:
        name: docker
        state: present
        executable: pip3

    - name: Login on dockerhub
      command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

    - name: Clone git repo
      git:
        repo: "https://github.com/v-kamerdinerov/boxfuse.git"
        dest: "/work"
        version: master

    - name: Build java app
      command: mvn clean package
      args:
        chdir: "/work"

    - name: Build and push docker image
      docker_image:
        build:
          path: /work
        name: anakin174/boxfuse-exam
        push: yes
        source: build

