---
- name: Prod stage
  hosts: prod
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Ensure prod apps is present
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - maven

    - name: Run docker image
        command: docker run -d -p 8080:8080 amalin174/boxfuse-exam:latest